
import java.util.Date;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author SANJAYA
 */
public class FOOD extends javax.swing.JFrame {

    /**
     * Creates new form FOOD
     */
    public FOOD() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton6 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        PN1 = new javax.swing.JTextField();
        PP1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        PN2 = new javax.swing.JTextField();
        PP2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        PN3 = new javax.swing.JTextField();
        PP3 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        PN4 = new javax.swing.JTextField();
        PP4 = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        area = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton6.setBackground(new java.awt.Color(53, 53, 53));
        jButton6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("Back");
        jButton6.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton6.setBorderPainted(false);
        jButton6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1039, 11, 93, 48));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 21)); // NOI18N
        jLabel1.setText("Food");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 172, 72, 36));
        getContentPane().add(PN1, new org.netbeans.lib.awtextra.AbsoluteConstraints(269, 176, 192, 36));
        getContentPane().add(PP1, new org.netbeans.lib.awtextra.AbsoluteConstraints(522, 176, 192, 36));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 21)); // NOI18N
        jLabel2.setText("Drink");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 240, 72, 36));
        getContentPane().add(PN2, new org.netbeans.lib.awtextra.AbsoluteConstraints(269, 240, 192, 36));
        getContentPane().add(PP2, new org.netbeans.lib.awtextra.AbsoluteConstraints(522, 240, 192, 36));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 21)); // NOI18N
        jLabel3.setText("Others");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 305, 72, 36));
        getContentPane().add(PN3, new org.netbeans.lib.awtextra.AbsoluteConstraints(269, 309, 192, 36));
        getContentPane().add(PP3, new org.netbeans.lib.awtextra.AbsoluteConstraints(522, 309, 192, 36));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 21)); // NOI18N
        jLabel4.setText("Home Delivery");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 373, 160, 36));
        getContentPane().add(PN4, new org.netbeans.lib.awtextra.AbsoluteConstraints(269, 373, 192, 36));
        getContentPane().add(PP4, new org.netbeans.lib.awtextra.AbsoluteConstraints(522, 373, 192, 36));

        jButton7.setBackground(new java.awt.Color(53, 53, 53));
        jButton7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setText("Generate Receipt");
        jButton7.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton7.setBorderPainted(false);
        jButton7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(381, 477, 149, 48));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Product Name");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(305, 137, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Product Price");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(553, 137, -1, -1));

        jLabel7.setFont(new java.awt.Font("Showcard Gothic", 0, 30)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setText("Bill receipt Printing System");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(387, 58, -1, -1));

        jButton8.setBackground(new java.awt.Color(53, 53, 53));
        jButton8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setText("Print");
        jButton8.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton8.setBorderPainted(false);
        jButton8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(565, 477, 149, 48));

        jButton9.setBackground(new java.awt.Color(53, 53, 53));
        jButton9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton9.setForeground(new java.awt.Color(255, 255, 255));
        jButton9.setText("Reset");
        jButton9.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton9.setBorderPainted(false);
        jButton9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(192, 477, 149, 48));

        area.setColumns(20);
        area.setRows(5);
        jScrollPane1.setViewportView(area);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(759, 137, 373, 418));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fooddd.png"))); // NOI18N
        jLabel8.setPreferredSize(new java.awt.Dimension(1000, 600));
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1, -1, 750));

        setSize(new java.awt.Dimension(1154, 593));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        Menu m = new Menu();
        m.setVisible(true);
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        
        
        area.setText("******************************************************************\n");
        area.setText(area.getText() +"*                                     Fees Receipt System                              *\n");
        area.setText(area.getText()+ "******************************************************************\n");
        
        Date odj = new Date();
        String date = odj.toString();
        
        //int nettotal = (PP1.getText()+PP2.getText()+PP3.getText()+PP4.getText());
        
        
        area.setText(area.getText()+ "      "+date+"\n \n \n ");
        area.setText(area.getText()+ "Product Name                 Product Price(Rs)"+"\n \n ");
        area.setText(area.getText() + PN1.getText()+"                                       "+PP1.getText()+"\n");
        area.setText(area.getText() + PN2.getText()+"                                       "+PP2.getText()+"\n");
        area.setText(area.getText() + PN3.getText()+"                                       "+PP3.getText()+"\n");
        area.setText(area.getText() + PN4.getText()+"                                       "+PP4.getText()+"\n\n\n\n\n\n\n");
        //area.setText(area.getText() + "Fees Amount :"+fees.getText()+"\n");
        area.setText(area.getText() +"NET ToTal :" +"\n\n" );
        
        area.setText(area.getText()+"\n                                                                                           Signature\n");
        
        area.setText(area.getText()+ "*******************************************************************\n");
        area.setText(area.getText()+ "                                 System by Sanjaya                               ");
        
        
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        try {
            area.print();
            
        } catch (Exception e) {
            
        } // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
         JOptionPane.showMessageDialog(null,"Do you want to Reset of the details?");
        
       area.setText("");
       PN1.setText("");
       PN2.setText("");
       PN3.setText("");
       PN4.setText("");
       PP1.setText("");
       PP2.setText("");
       PP3.setText("");
       PP4.setText("");
    }//GEN-LAST:event_jButton9ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FOOD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FOOD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FOOD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FOOD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FOOD().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField PN1;
    private javax.swing.JTextField PN2;
    private javax.swing.JTextField PN3;
    private javax.swing.JTextField PN4;
    private javax.swing.JTextField PP1;
    private javax.swing.JTextField PP2;
    private javax.swing.JTextField PP3;
    private javax.swing.JTextField PP4;
    private javax.swing.JTextArea area;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
